
export type FoodItem = {
  name: string;
  description: string;
  subcategory: string;
  menus: string;
  sizes: { size: string; price: string }[];
  modifierGroups: string;
};

export const allItems: FoodItem[] = [
  // Appetizers
  {
    name: "Spinach Artichoke Dip",
    description: "Creamy spinach and artichoke dip served with tortilla chips.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "12.99" }],
    modifierGroups: "",
  },
  {
    name: "Bruschetta",
    description: "Toasted baguette slices topped with fresh tomatoes, garlic, basil, and balsamic glaze.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "10.50" }],
    modifierGroups: "",
  },
  {
    name: "Loaded Nachos",
    description: "Tortilla chips smothered in cheese, beans, jalapeños, sour cream, and guacamole.",
    subcategory: "Appetizers",
    menus: "Dinner, Late Night, Happy Hour",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "Add Protein",
  },
  {
    name: "Chicken Wings",
    description: "Crispy chicken wings tossed in your choice of Buffalo, BBQ, or Teriyaki sauce.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [
      { size: "6 pieces", price: "11.00" },
      { size: "12 pieces", price: "20.00" },
    ],
    modifierGroups: "Sauces",
  },
  {
    name: "Mozzarella Sticks",
    description: "Fried mozzarella sticks served with marinara sauce.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner, Kids Menu",
    sizes: [{ size: "Regular", price: "9.50" }],
    modifierGroups: "",
  },

  // Soups
  {
    name: "Tomato Basil Soup",
    description: "Classic creamy tomato soup with fresh basil.",
    subcategory: "Soups",
    menus: "Lunch, Dinner",
    sizes: [
      { size: "Cup", price: "5.00" },
      { size: "Bowl", price: "8.00" },
    ],
    modifierGroups: "",
  },
  {
    name: "French Onion Soup",
    description: "Rich beef broth with caramelized onions, topped with a crouton and melted Gruyère cheese.",
    subcategory: "Soups",
    menus: "Dinner",
    sizes: [{ size: "Bowl", price: "9.00" }],
    modifierGroups: "",
  },

  // Salads
  {
    name: "Caesar Salad",
    description: "Crisp romaine lettuce, parmesan cheese, croutons, and Caesar dressing.",
    subcategory: "Salads",
    menus: "Lunch, Dinner",
    sizes: [
      { size: "Side", price: "7.00" },
      { size: "Full", price: "12.00" },
    ],
    modifierGroups: "Add Protein",
  },
  {
    name: "Cobb Salad",
    description: "Mixed greens with grilled chicken, bacon, avocado, egg, tomatoes, and blue cheese dressing.",
    subcategory: "Salads",
    menus: "Lunch",
    sizes: [{ size: "Full", price: "16.50" }],
    modifierGroups: "",
  },
  {
    name: "Greek Salad",
    description: "Romaine lettuce, cucumbers, tomatoes, red onions, olives, and feta cheese with a lemon-herb vinaigrette.",
    subcategory: "Salads",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Full", price: "14.00" }],
    modifierGroups: "Add Protein",
  },

  // Sandwiches
  {
    name: "Turkey Club",
    description: "Triple-decker sandwich with turkey, bacon, lettuce, tomato, and mayonnaise.",
    subcategory: "Sandwiches",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Philly Cheesesteak",
    description: "Thinly sliced steak with grilled onions and melted provolone cheese on a hoagie roll.",
    subcategory: "Sandwiches",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "Sides, Extra Toppings",
  },
  {
    name: "Caprese Panini",
    description: "Fresh mozzarella, tomatoes, and basil pesto pressed in a warm panini.",
    subcategory: "Sandwiches",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "13.50" }],
    modifierGroups: "Sides",
  },

  // Burgers
  {
    name: "Classic Burger",
    description: "A juicy beef patty with lettuce, tomato, and our special sauce.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "14.99" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "Bacon Cheeseburger",
    description: "Our classic burger topped with crispy bacon and your choice of cheese.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner, Late Night",
    sizes: [{ size: "Regular", price: "16.50" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "Mushroom Swiss Burger",
    description: "Beef patty topped with sautéed mushrooms and melted Swiss cheese.",
    subcategory: "Burgers",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "15.75" }],
    modifierGroups: "Toppings, Sides",
  },

  // Pizza
  {
    name: "Margherita Pizza",
    description: "Fresh mozzarella, basil, and tomato sauce on a thin crust.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
      { size: '12"', price: "18.50" },
      { size: '16"', price: "24.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Pepperoni Pizza",
    description: "Classic pizza with a generous amount of pepperoni and mozzarella.",
    subcategory: "Pizza",
    menus: "Lunch, Dinner, Late Night",
    sizes: [
      { size: '12"', price: "20.00" },
      { size: '16"', price: "26.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "BBQ Chicken Pizza",
    description: "Grilled chicken, red onions, cilantro, and BBQ sauce.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
      { size: '12"', price: "22.00" },
      { size: '16"', price: "28.00" },
    ],
    modifierGroups: "Crust Type",
  },

  // Pasta
  {
    name: "Fettuccine Alfredo",
    description: "Fettuccine pasta in a creamy parmesan sauce.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "17.00" }],
    modifierGroups: "Add Protein",
  },
  {
    name: "Spaghetti and Meatballs",
    description: "Classic spaghetti with homemade meatballs and marinara sauce.",
    subcategory: "Pasta",
    menus: "Dinner, Kids Menu",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  {
    name: "Pesto Penne",
    description: "Penne pasta tossed in a fresh basil pesto sauce with cherry tomatoes.",
    subcategory: "Pasta",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "Add Protein",
  },

  // Entrees
  {
    name: "Grilled Salmon",
    description: "Grilled salmon fillet served with roasted asparagus and lemon-dill sauce.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "25.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Filet Mignon",
    description: "8oz filet mignon cooked to perfection, served with mashed potatoes and green beans.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "8oz", price: "42.00" }],
    modifierGroups: "Sides, Sauces",
  },
  {
    name: "Chicken Parmesan",
    description: "Breaded chicken breast topped with marinara and melted mozzarella, served with spaghetti.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "22.00" }],
    modifierGroups: "",
  },

  // Desserts
  {
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten center, served with vanilla ice cream.",
    subcategory: "Desserts",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "New York Cheesecake",
    description: "Classic cheesecake with a graham cracker crust, topped with strawberries.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Slice", price: "8.50" }],
    modifierGroups: "",
  },
  {
    name: "Tiramisu",
    description: "Coffee-soaked ladyfingers layered with a whipped mixture of eggs, sugar, and mascarpone cheese.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "9.50" }],
    modifierGroups: "",
  },
  
  // Cocktails
  {
    name: "Old Fashioned",
    description: "Whiskey, sugar, bitters, and a twist of citrus.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Late Night, Happy Hour",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "",
  },
  {
    name: "Margarita",
    description: "Tequila, lime juice, and triple sec.",
    subcategory: "Margaritas",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "Extra Toppings",
  },
  {
    name: "Mojito",
    description: "White rum, sugar, lime juice, soda water, and mint.",
    subcategory: "Mojitos",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Espresso Martini",
    description: "Vodka, coffee liqueur, and a shot of espresso.",
    subcategory: "Martinis",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "Spicy Margarita",
    description: "Tequila, lime, jalapeño simple syrup, and a tajin rim.",
    subcategory: "Margaritas",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "",
  },
  {
    name: "Lemon Drop Shot",
    description: "Vodka, lemon juice, simple syrup.",
    subcategory: "Shots",
    menus: "Late Night, Happy Hour",
    sizes: [{ size: "Shot", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Lavender Haze",
    description: "Gin, lavender syrup, lemon juice, and a splash of soda.",
    subcategory: "Signature Cocktails",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "",
  },
  
  // Beer
  {
    name: "Local IPA",
    description: "A hoppy and bitter India Pale Ale from a local brewery.",
    subcategory: "Draft Beer",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Pint", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Light Lager",
    description: "A crisp and refreshing light lager.",
    subcategory: "Bottled Beer",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Bottle", price: "6.00" }],
    modifierGroups: "",
  },
  {
    name: "Guinness",
    description: "A rich and creamy Irish stout.",
    subcategory: "Canned Beer",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Can", price: "7.50" }],
    modifierGroups: "",
  },
  {
    name: "Angry Orchard",
    description: "A sweet and crisp hard cider.",
    subcategory: "Cider",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Bottle", price: "7.00" }],
    modifierGroups: "",
  },
  {
    name: "High Noon",
    description: "A popular hard seltzer.",
    subcategory: "RTDs (Ready-to-Drink)",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Can", price: "9.00" }],
    modifierGroups: "",
  },

  // Wine
  {
    name: "Cabernet Sauvignon",
    description: "A full-bodied red wine with dark fruit notes.",
    subcategory: "Red Wine",
    menus: "Dinner",
    sizes: [
      { size: "Glass", price: "14.00" },
      { size: "Bottle", price: "52.00" },
    ],
    modifierGroups: "",
  },
  {
    name: "Chardonnay",
    description: "A dry, medium- to full-bodied white wine.",
    subcategory: "White Wine",
    menus: "Lunch, Dinner",
    sizes: [
      { size: "Glass", price: "12.00" },
      { size: "Bottle", price: "45.00" },
    ],
    modifierGroups: "",
  },
  {
    name: "Provence Rosé",
    description: "A light and dry rosé from the south of France.",
    subcategory: "Rosé Wine",
    menus: "Lunch, Happy Hour",
    sizes: [
      { size: "Glass", price: "13.00" },
      { size: "Bottle", price: "48.00" },
    ],
    modifierGroups: "",
  },
  {
    name: "Prosecco",
    description: "A sparkling white wine from Italy.",
    subcategory: "Sparkling Wine",
    menus: "Brunch, Dinner, Happy Hour",
    sizes: [
      { size: "Glass", price: "11.00" },
      { size: "Bottle", price: "40.00" },
    ],
    modifierGroups: "",
  },

  // Liquor
  {
    name: "Maker's Mark",
    description: "A premium bourbon whiskey.",
    subcategory: "Whiskey",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Shot", price: "12.00" }],
    modifierGroups: "",
  },
  {
    name: "Tito's Handmade Vodka",
    description: "A popular American vodka.",
    subcategory: "Vodka",
    menus: "Dinner, Late Night, Happy Hour",
    sizes: [{ size: "Shot", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Hendrick's Gin",
    description: "A premium gin infused with cucumber and rose.",
    subcategory: "Gin",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Shot", price: "11.00" }],
    modifierGroups: "",
  },
  {
    name: "Captain Morgan",
    description: "A popular spiced rum.",
    subcategory: "Rum",
    menus: "Late Night, Happy Hour",
    sizes: [{ size: "Shot", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Don Julio 1942",
    description: "An ultra-premium añejo tequila.",
    subcategory: "Tequila",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Shot", price: "35.00" }],
    modifierGroups: "",
  },
  {
    name: "Aperol",
    description: "An Italian bitter apéritif.",
    subcategory: "Liqueurs",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Shot", price: "9.00" }],
    modifierGroups: "",
  },

  // N/A + Mocktails
  {
    name: "Latte",
    description: "Espresso with steamed milk.",
    subcategory: "Coffee",
    menus: "Brunch, Lunch",
    sizes: [{ size: "Regular", price: "5.00" }],
    modifierGroups: "Milk Options, Syrups",
  },
  {
    name: "Iced Tea",
    description: "Freshly brewed black iced tea.",
    subcategory: "Tea",
    menus: "Brunch, Lunch, Dinner",
    sizes: [{ size: "Regular", price: "3.50" }],
    modifierGroups: "",
  },
  {
    name: "Orange Juice",
    description: "Freshly squeezed orange juice.",
    subcategory: "Juice",
    menus: "Brunch, Lunch",
    sizes: [{ size: "Regular", price: "4.50" }],
    modifierGroups: "",
  },
  {
    name: "Coke",
    description: "Classic Coca-Cola.",
    subcategory: "Soda",
    menus: "Brunch, Lunch, Dinner, Late Night",
    sizes: [{ size: "Regular", price: "3.00" }],
    modifierGroups: "",
  },
  {
    name: "Virgin Mojito",
    description: "Mint, lime, sugar, and soda water.",
    subcategory: "Mocktails",
    menus: "Brunch, Lunch, Dinner",
    sizes: [{ size: "Regular", price: "8.00" }],
    modifierGroups: "",
  },

  // Merchandise
  {
    name: "Branded T-Shirt",
    description: "A comfortable t-shirt with our logo.",
    subcategory: "Apparel",
    menus: "Merchandise",
    sizes: [
        { size: "S", price: "25.00"},
        { size: "M", price: "25.00"},
        { size: "L", price: "25.00"},
        { size: "XL", price: "25.00"},
    ],
    modifierGroups: "",
  },
  {
    name: "Pint Glass",
    description: "A branded pint glass.",
    subcategory: "Glassware",
    menus: "Merchandise",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "",
  },
  {
    name: "Tote Bag",
    description: "A stylish tote bag for your everyday needs.",
    subcategory: "Other",
    menus: "Merchandise",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  // Add 150 more items to reach over 200
  // Appetizers (15 more)
  {
    name: "Calamari Fritti",
    description: "Lightly breaded and fried calamari served with a spicy aioli.",
    subcategory: "Appetizers",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "Garlic Knots",
    description: "Soft bread knots tossed in garlic butter and parmesan.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "6 pieces", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Ahi Tuna Poke",
    description: "Diced ahi tuna, avocado, and cucumber in a soy-ginger marinade.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  {
    name: "Shrimp Cocktail",
    description: "Chilled jumbo shrimp served with a zesty cocktail sauce.",
    subcategory: "Appetizers",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "",
  },
  {
    name: "Queso Fundido",
    description: "Melted cheese with chorizo, served with warm tortillas.",
    subcategory: "Appetizers",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Stuffed Mushrooms",
    description: "Mushroom caps filled with a savory mixture of breadcrumbs, herbs, and cheese.",
    subcategory: "Appetizers",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "11.50" }],
    modifierGroups: "",
  },
  {
    name: "Potstickers",
    description: "Pan-fried dumplings filled with pork and vegetables, served with a dipping sauce.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "6 pieces", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Fried Pickles",
    description: "Crispy fried pickle spears served with ranch dressing.",
    subcategory: "Appetizers",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Crab Cakes",
    description: "Two lump crab cakes pan-seared and served with a remoulade sauce.",
    subcategory: "Appetizers",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "19.00" }],
    modifierGroups: "",
  },
  {
    name: "Edamame",
    description: "Steamed edamame pods sprinkled with sea salt.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "7.00" }],
    modifierGroups: "",
  },
  {
    name: "Onion Rings",
    description: "Thick-cut onion rings, beer-battered and fried to a golden brown.",
    subcategory: "Sides",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "8.50" }],
    modifierGroups: "",
  },
  {
    name: "Soft Pretzel",
    description: "A large, warm soft pretzel served with cheese sauce and mustard.",
    subcategory: "Appetizers",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Hummus Platter",
    description: "Creamy hummus served with pita bread, cucumber, and carrots.",
    subcategory: "Appetizers",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "",
  },
  {
    name: "Spring Rolls",
    description: "Crispy vegetable spring rolls served with a sweet chili sauce.",
    subcategory: "Appetizers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "4 pieces", price: "9.50" }],
    modifierGroups: "",
  },
  {
    name: "Bavarian Pretzel Sticks",
    description: "Warm and soft pretzel sticks with a side of beer cheese.",
    subcategory: "Appetizers",
    menus: "Happy Hour, Lunch",
    sizes: [{ size: "Regular", price: "11.00" }],
    modifierGroups: "",
  },
  
  // Soups (3 more)
  {
    name: "Clam Chowder",
    description: "Creamy New England style clam chowder.",
    subcategory: "Soups",
    menus: "Lunch, Dinner",
    sizes: [
        { size: "Cup", price: "6.00" },
        { size: "Bowl", price: "9.50" },
    ],
    modifierGroups: "",
  },
  {
    name: "Chicken Noodle Soup",
    description: "A comforting classic with chicken, vegetables, and noodles.",
    subcategory: "Soups",
    menus: "Lunch",
    sizes: [{ size: "Bowl", price: "7.50" }],
    modifierGroups: "",
  },
  {
    name: "Miso Soup",
    description: "Traditional Japanese soup with tofu, seaweed, and scallions.",
    subcategory: "Soups",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Cup", price: "4.00" }],
    modifierGroups: "",
  },

  // Salads (7 more)
  {
    name: "Spinach Salad",
    description: "Baby spinach with bacon, mushrooms, egg, and a warm bacon vinaigrette.",
    subcategory: "Salads",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Full", price: "14.50" }],
    modifierGroups: "Add Protein",
  },
  {
    name: "Wedge Salad",
    description: "A crisp wedge of iceberg lettuce with blue cheese dressing, bacon, and tomatoes.",
    subcategory: "Salads",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "11.00" }],
    modifierGroups: "",
  },
  {
    name: "Quinoa Salad",
    description: "Quinoa with mixed vegetables, chickpeas, and a lemon-tahini dressing.",
    subcategory: "Salads",
    menus: "Lunch",
    sizes: [{ size: "Full", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Asian Chicken Salad",
    description: "Grilled chicken, mixed greens, mandarin oranges, and crispy wontons with a sesame ginger dressing.",
    subcategory: "Salads",
    menus: "Lunch",
    sizes: [{ size: "Full", price: "16.00" }],
    modifierGroups: "",
  },
  {
    name: "House Salad",
    description: "Mixed greens with cucumber, tomatoes, and carrots with your choice of dressing.",
    subcategory: "Salads",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Side", price: "6.00" }],
    modifierGroups: "",
  },
  {
    name: "Beet Salad",
    description: "Roasted beets, goat cheese, walnuts, and arugula with a balsamic vinaigrette.",
    subcategory: "Salads",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "13.50" }],
    modifierGroups: "",
  },
  {
    name: "Taco Salad",
    description: "A crispy tortilla bowl filled with seasoned ground beef, lettuce, tomatoes, cheese, and salsa.",
    subcategory: "Salads",
    menus: "Lunch",
    sizes: [{ size: "Full", price: "15.00" }],
    modifierGroups: "",
  },
  
  // Sandwiches (7 more)
  {
    name: "Reuben Sandwich",
    description: "Corned beef, Swiss cheese, sauerkraut, and Russian dressing on rye bread.",
    subcategory: "Sandwiches",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "15.50" }],
    modifierGroups: "Sides",
  },
  {
    name: "BLT Sandwich",
    description: "Crispy bacon, lettuce, and tomato with mayonnaise on toasted white bread.",
    subcategory: "Sandwiches",
    menus: "Lunch, Brunch",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "French Dip",
    description: "Thinly sliced roast beef on a French roll, served with a side of au jus.",
    subcategory: "Sandwiches",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "16.50" }],
    modifierGroups: "Sides",
  },
  {
    name: "Grilled Cheese",
    description: "A classic grilled cheese with cheddar and American cheese.",
    subcategory: "Sandwiches",
    menus: "Lunch, Kids Menu",
    sizes: [{ size: "Regular", price: "10.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Chicken Salad Sandwich",
    description: "Homemade chicken salad with lettuce on a croissant.",
    subcategory: "Sandwiches",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Veggie Wrap",
    description: "A wrap filled with hummus, mixed greens, cucumber, tomatoes, and avocado.",
    subcategory: "Sandwiches",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "12.50" }],
    modifierGroups: "Sides",
  },
  {
    name: "Pulled Pork Sandwich",
    description: "Slow-cooked pulled pork in a tangy BBQ sauce on a brioche bun.",
    subcategory: "Sandwiches",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "14.50" }],
    modifierGroups: "Sides",
  },

  // Burgers (7 more)
  {
    name: "Veggie Burger",
    description: "A plant-based patty with lettuce, tomato, and onion.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "Jalapeño Burger",
    description: "A spicy burger with jalapeños, pepper jack cheese, and a chipotle aioli.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "Blue Cheese Burger",
    description: "Topped with blue cheese crumbles and caramelized onions.",
    subcategory: "Burgers",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "16.25" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "BBQ Bacon Burger",
    description: "A beef patty with BBQ sauce, bacon, and an onion ring.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "17.00" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "California Burger",
    description: "Topped with avocado, sprouts, and Swiss cheese.",
    subcategory: "Burgers",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "16.50" }],
    modifierGroups: "Toppings, Sides",
  },
  {
    name: "Slider Trio",
    description: "Three mini burgers: classic, bacon cheese, and mushroom Swiss.",
    subcategory: "Burgers",
    menus: "Happy Hour",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "Patty Melt",
    description: "A beef patty with grilled onions and Swiss cheese on rye bread.",
    subcategory: "Burgers",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "Sides",
  },
  
  // Pizza (7 more)
  {
    name: "Meat Lovers Pizza",
    description: "Pepperoni, sausage, bacon, and ham.",
    subcategory: "Pizza",
    menus: "Dinner, Late Night",
    sizes: [
        { size: '12"', price: "24.00" },
        { size: '16"', price: "30.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Veggie Supreme Pizza",
    description: "Bell peppers, onions, mushrooms, olives, and tomatoes.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
        { size: '12"', price: "21.00" },
        { size: '16"', price: "27.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Hawaiian Pizza",
    description: "A classic combination of ham and pineapple.",
    subcategory: "Pizza",
    menus: "Lunch, Dinner",
    sizes: [
        { size: '12"', price: "20.50" },
        { size: '16"', price: "26.50" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "White Pizza",
    description: "Ricotta cheese, mozzarella, garlic, and olive oil.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
        { size: '12"', price: "19.00" },
        { size: '16"', price: "25.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Buffalo Chicken Pizza",
    description: "Buffalo chicken, mozzarella, and a drizzle of ranch.",
    subcategory: "Pizza",
    menus: "Dinner, Late Night",
    sizes: [
        { size: '12"', price: "22.50" },
        { size: '16"', price: "28.50" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Four Cheese Pizza",
    description: "A blend of mozzarella, parmesan, provolone, and ricotta.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
        { size: '12"', price: "20.00" },
        { size: '16"', price: "26.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },
  {
    name: "Pesto Pizza",
    description: "Pesto base with grilled chicken, sun-dried tomatoes, and mozzarella.",
    subcategory: "Pizza",
    menus: "Dinner",
    sizes: [
        { size: '12"', price: "23.00" },
        { size: '16"', price: "29.00" },
    ],
    modifierGroups: "Crust Type, Extra Toppings",
  },

  // Pasta (7 more)
  {
    name: "Lasagna",
    description: "Layers of pasta, meat sauce, ricotta, and mozzarella.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "20.00" }],
    modifierGroups: "",
  },
  {
    name: "Shrimp Scampi",
    description: "Shrimp sautéed in a garlic butter and white wine sauce over linguine.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "23.00" }],
    modifierGroups: "",
  },
  {
    name: "Carbonara",
    description: "Spaghetti with a creamy egg sauce, pancetta, and parmesan.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "19.00" }],
    modifierGroups: "",
  },
  {
    name: "Baked Ziti",
    description: "Ziti pasta baked with marinara sauce, ricotta, and mozzarella.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "18.50" }],
    modifierGroups: "",
  },
  {
    name: "Ravioli",
    description: "Cheese-filled ravioli in a tomato cream sauce.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  {
    name: "Gnocchi",
    description: "Potato gnocchi in a brown butter sage sauce.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "19.50" }],
    modifierGroups: "",
  },
  {
    name: "Cacio e Pepe",
    description: "Spaghetti with a simple sauce of black pepper and Pecorino Romano cheese.",
    subcategory: "Pasta",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "",
  },

  // Entrees (7 more)
  {
    name: "Ribeye Steak",
    description: "A 12oz ribeye steak, grilled to order, served with a baked potato.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "12oz", price: "38.00" }],
    modifierGroups: "Sides, Sauces",
  },
  {
    name: "Fish and Chips",
    description: "Beer-battered cod served with french fries and tartar sauce.",
    subcategory: "Entrees",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "19.00" }],
    modifierGroups: "",
  },
  {
    name: "Shepherd's Pie",
    description: "A savory pie of ground lamb and vegetables, topped with mashed potatoes.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  {
    name: "Roasted Chicken",
    description: "Half a roasted chicken served with root vegetables.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "23.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Pork Chops",
    description: "Grilled pork chops with an apple chutney, served with sweet potato mash.",
    subcategory: "Entrees",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "24.00" }],
    modifierGroups: "Sides",
  },
  {
    name: "Tacos",
    description: "Three tacos with your choice of carnitas, chicken, or fish, on corn tortillas.",
    subcategory: "Entrees",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "Vegetable Stir-fry",
    description: "A mix of fresh vegetables stir-fried in a savory sauce, served with rice.",
    subcategory: "Entrees",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "Add Protein",
  },

  // Desserts (7 more)
  {
    name: "Apple Pie",
    description: "A classic apple pie served warm with a scoop of vanilla ice cream.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Slice", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Crème Brûlée",
    description: "A rich custard base topped with a layer of hardened caramelized sugar.",
    subcategory: "Desserts",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Brownie Sundae",
    description: "A warm brownie topped with ice cream, hot fudge, and whipped cream.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Key Lime Pie",
    description: "A sweet and tart key lime pie in a graham cracker crust.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Slice", price: "8.50" }],
    modifierGroups: "",
  },
  {
    name: "Ice Cream",
    description: "Your choice of vanilla, chocolate, or strawberry.",
    subcategory: "Desserts",
    menus: "Lunch, Dinner, Kids Menu",
    sizes: [
        { size: "1 scoop", price: "4.00" },
        { size: "2 scoops", price: "6.00" },
    ],
    modifierGroups: "",
  },
  {
    name: "Bread Pudding",
    description: "Warm bread pudding with a caramel sauce.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Sorbet",
    description: "A refreshing lemon or raspberry sorbet.",
    subcategory: "Desserts",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "7.00" }],
    modifierGroups: "",
  },

  // Sides (5 more)
  {
    name: "French Fries",
    description: "Crispy, golden french fries.",
    subcategory: "Sides",
    menus: "Lunch, Dinner, Kids Menu",
    sizes: [{ size: "Regular", price: "6.00" }],
    modifierGroups: "",
  },
  {
    name: "Mashed Potatoes",
    description: "Creamy, buttery mashed potatoes.",
    subcategory: "Sides",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "6.00" }],
    modifierGroups: "",
  },
  {
    name: "Steamed Vegetables",
    description: "A mix of seasonal steamed vegetables.",
    subcategory: "Sides",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "6.00" }],
    modifierGroups: "",
  },
  {
    name: "Mac and Cheese",
    description: "A creamy, cheesy macaroni and cheese.",
    subcategory: "Sides",
    menus: "Lunch, Dinner, Kids Menu",
    sizes: [{ size: "Regular", price: "7.00" }],
    modifierGroups: "",
  },
  {
    name: "Side Salad",
    description: "A small salad with mixed greens, tomatoes, and cucumber.",
    subcategory: "Sides",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "5.00" }],
    modifierGroups: "",
  },

  // Kids Menu (5 more)
  {
    name: "Chicken Tenders",
    description: "Breaded chicken tenders served with fries.",
    subcategory: "Kids Menu",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Mini Pizza",
    description: "A small cheese or pepperoni pizza.",
    subcategory: "Kids Menu",
    menus: "Lunch, Dinner",
    sizes: [{ size: "Regular", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Hot Dog",
    description: "A classic hot dog in a bun, served with fries.",
    subcategory: "Kids Menu",
    menus: "Lunch",
    sizes: [{ size: "Regular", price: "8.00" }],
    modifierGroups: "",
  },
  {
    name: "Buttered Noodles",
    description: "Simple pasta with butter and parmesan cheese.",
    subcategory: "Kids Menu",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "7.00" }],
    modifierGroups: "",
  },
  {
    name: "Fruit Cup",
    description: "A mix of fresh seasonal fruit.",
    subcategory: "Kids Menu",
    menus: "Brunch, Lunch, Dinner",
    sizes: [{ size: "Regular", price: "5.00" }],
    modifierGroups: "",
  },

  // Cocktails (20 more)
  {
    name: "Manhattan",
    description: "Rye whiskey, sweet vermouth, and bitters.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "",
  },
  {
    name: "Negroni",
    description: "Gin, Campari, and sweet vermouth.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Whiskey Sour",
    description: "Whiskey, lemon juice, and simple syrup, often with an egg white.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Daiquiri",
    description: "Rum, lime juice, and simple syrup.",
    subcategory: "Classic Cocktails",
    menus: "Happy Hour",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "",
  },
  {
    name: "Cosmopolitan",
    description: "Vodka, triple sec, cranberry juice, and lime juice.",
    subcategory: "Martinis",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "",
  },
  {
    name: "Tom Collins",
    description: "Gin, lemon juice, simple syrup, and soda water.",
    subcategory: "Classic Cocktails",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "12.00" }],
    modifierGroups: "",
  },
  {
    name: "Paloma",
    description: "Tequila and grapefruit soda.",
    subcategory: "Classic Cocktails",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "11.00" }],
    modifierGroups: "",
  },
  {
    name: "Aperol Spritz",
    description: "Aperol, prosecco, and a splash of soda.",
    subcategory: "Signature Cocktails",
    menus: "Brunch, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Moscow Mule",
    description: "Vodka, ginger beer, and lime juice, served in a copper mug.",
    subcategory: "Signature Cocktails",
    menus: "Lunch, Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Green Tea Shot",
    description: "Jameson, peach schnapps, and sour mix.",
    subcategory: "Shots",
    menus: "Late Night, Happy Hour",
    sizes: [{ size: "Shot", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Jägerbomb",
    description: "A shot of Jägermeister dropped into a glass of Red Bull.",
    subcategory: "Shots",
    menus: "Late Night",
    sizes: [{ size: "Shot", price: "10.00" }],
    modifierGroups: "",
  },
  {
    name: "Pineapple Upside Down Cake Shot",
    description: "Vanilla vodka, pineapple juice, and a drop of grenadine.",
    subcategory: "Shots",
    menus: "Late Night, Happy Hour",
    sizes: [{ size: "Shot", price: "9.00" }],
    modifierGroups: "",
  },
  {
    name: "Cadillac Margarita",
    description: "A premium margarita with top-shelf tequila and a float of Grand Marnier.",
    subcategory: "Margaritas",
    menus: "Dinner",
    sizes: [{ size: "Regular", price: "18.00" }],
    modifierGroups: "",
  },
  {
    name: "Strawberry Margarita",
    description: "A frozen margarita blended with fresh strawberries.",
    subcategory: "Margaritas",
    menus: "Lunch, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Dirty Martini",
    description: "A classic martini with a splash of olive brine.",
    subcategory: "Martinis",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "Vesper Martini",
    description: "Gin, vodka, and Lillet Blanc, shaken, not stirred.",
    subcategory: "Martinis",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "",
  },
  {
    name: "Dark 'n' Stormy",
    description: "Dark rum and ginger beer with a lime wedge.",
    subcategory: "Signature Cocktails",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "13.00" }],
    modifierGroups: "",
  },
  {
    name: "Bee's Knees",
    description: "Gin, lemon juice, and honey syrup.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Happy Hour",
    sizes: [{ size: "Regular", price: "14.00" }],
    modifierGroups: "",
  },
  {
    name: "Sidecar",
    description: "Cognac, triple sec, and lemon juice.",
    subcategory: "Classic Cocktails",
    menus: "Dinner, Late Night",
    sizes: [{ size: "Regular", price: "15.00" }],
    modifierGroups: "",
  },
  {
    name: "French 75",
    description: "Gin, lemon juice, simple syrup, and champagne.",
    subcategory: "Signature Cocktails",
    menus: "Brunch, Dinner",
    sizes: [{ size: "Regular", price: "16.00" }],
    modifierGroups: "",
  },
];
